on:
  push:
    paths:
    - terradock/**
    - .github/workflows/**

name: Terradock

jobs:
  docker:
    name: Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      if: github.ref != 'refs/heads/master'
      run: |
        cd terradock
        bash build_or_push.sh build

    - name: Login to DockerHub
      if: github.ref == 'refs/heads/master'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push
      if: github.ref == 'refs/heads/master'
      run: |
        cd terradock
        bash build_or_push.sh build-and-push

