on:
  push:
    branches:
    - master
    paths:
    - terradock/**
  pull_request:
    branches:
    - master
    paths:
    - terradock/**

name: Terradock

jobs:
  docker:
    name: Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push 
      run: |
        cd terradock
        bash build_and_push.sh

